import '@fontsource/noto-sans-sc/chinese-simplified-400.css'
import '@fontsource/noto-sans-sc/latin-400.css'

export { Player, mountPlayer } from './core/player.ts'
export type { MountPlayerOptions } from './core/player.ts'
export { evaluateScene, validateProject, resolveParams } from './core/engine.ts'
export { projectFromBlob, projectToBlob } from './core/project-file.ts'
export { exportPng, exportFrames, exportVideo, resolveExportRange, supportedVideoType } from './core/export.ts'
export type { ExportRange } from './core/export.ts'
export { templates, createBlankProject } from './core/templates.ts'
export type { Project, Scene, SceneNode, Track, Parameter, EvaluatedScene } from './core/types.ts'
